siteName: CNX Agency
colorScheme: light
siteMode: local
aiProvider: openai
aiApiKey: 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
pexelsApiKey: ""
canonicalUrl: https://eletricistaemsalvadorprime.com.br
companyPhone: "71986710482"
companyWhatsapp: "71986710482"
generateSitemap: true
generateRobots: true
robotsDisallow:
  - /admin
  - /api
blogPermalinkStructure: postname
blogUrlPrefix: blog
autoUpdateEnabled: false
